from db_connect import DbConnect

class CabeceraModel:

    def __init__(self):
        self.conn = DbConnect().connect()

        if self.conn is None:
            raise ConnectionError("No se pudo establecer la conexi√≥n a la base de datos.")

        self.cursor = self.conn.cursor(dictionary=True)

    def create_cabecera(self, datos):
        sql = "INSERT INTO cabeceras (id_cabecera, proyecto, enfoque_estrategico, sector, objetivos, actividad) " \
        "VALUES (%s, %s, %s, %s, %s, %s)"
      
        try: 
            self.cursor.execute(sql, tuple(datos))
            self.conn.commit()
            return self.cursor.lastrowid

        except Exception as e:
            self.conn.rollback()
            print(f"Error inesperado: {e}")
            return None

    def update_cabecera(self, datos):
        sql = "UPDATE cabeceras SET proyecto = %s, enfoque_estrategico = %s, sector = %s, objetivos = %s, actividad = %s " \
        "WHERE id_cabecera = %s"
        
        try: 
            self.cursor.execute(sql, tuple(datos))
            self.conn.commit()
            return self.cursor.rowcount

        except Exception as e:
            self.conn.rollback()
            print(f"Error inesperado: {e}")
            return None

    def delete_cabecera(self, id):
        sql = "DELETE FROM cabeceras WHERE id_cabecera = %s"
        try: 
            self.cursor.execute(sql, (id))
            self.conn.commit()
            return self.cursor.rowcount

        except Exception as e:
            self.conn.rollback()
            print(f"Error inesperado: {e}")
            return None
